name: 버그 리포트 템플릿
description: 기능 개선을 위해 버그를 제보해주세요.
title: "fix: "
labels: ["bug"]
body: 
- type: textarea
  attributes: 
    label: 버그 설명
    description: 경험한 문제에 대해 상세히 적어주세요. (가능하다면 스크린샷도 함께 첨부해주세요)
  validations:
    required: true
- type: textarea
  attributes: 
    label: 기대 동작 설명
    description: 기대했던 동작 및 반응에 대해 상세히 적어주세요.
  validations:
    required: true
- type: textarea
  attributes: 
    label: 버그 재현법
    description: 문제를 재현하기 위한 방법을 적어주세요.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: false
- type: dropdown
  attributes: 
    label: 실행 환경 (OS)
    description: 문제가 발생했던 OS을 골라주세요.
    options:
      - Windows
      - MacOs
      - Linux
      - ETC...
  validations:
    required: true
- type: checkboxes
  attributes: 
    label: 실행 환경 (브라우저)
    description: 문제가 발생했던 브라우저을 골라주세요.
    options:
      - label: Chrome
      - label: Firefox
      - label: Edge
      - label: ETC...
  validations:
    required: true
- type: textarea
  attributes: 
    label: 기타 참고 사항
  validations:
    required: false

